This is a project which i recently developed when i was going through an online course on udemy. The course was React-The Complete Guide
(Redux, Hooks, React Router which helped me a lot in development of this project. This project is about an app(Burger Builder App) where
you can make your own burger and order it. You can see your orders on orders page but when you are already signed in. Otherwise first you 
have to authenticate yourself. For storing data in backend i used Google Firebase. I have given the link of github repository where you
can see the code of my project. And can use it to see the project.
Link:- https://github.com/abz1077/Burger-Builder-App
